// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAawBbigakkSzHZAt_mCAe0axLN9tHml6k',
    appId: '1:1060733275150:web:22c6ae26b1b82d7fcb805f',
    messagingSenderId: '1060733275150',
    projectId: 'fruit-app-ef788',
    authDomain: 'fruit-app-ef788.firebaseapp.com',
    storageBucket: 'fruit-app-ef788.firebasestorage.app',
    measurementId: 'G-RM5HY9YLCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJdhVU0sGMfp7jDnegmI2U3CcCOkZ9RrQ',
    appId: '1:1060733275150:android:59d233d7cfc53d6acb805f',
    messagingSenderId: '1060733275150',
    projectId: 'fruit-app-ef788',
    storageBucket: 'fruit-app-ef788.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd-ybuCjabdAGYr-8dXGkIRCefPJjhUjQ',
    appId: '1:1060733275150:ios:769e7898c41ed3c3cb805f',
    messagingSenderId: '1060733275150',
    projectId: 'fruit-app-ef788',
    storageBucket: 'fruit-app-ef788.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd-ybuCjabdAGYr-8dXGkIRCefPJjhUjQ',
    appId: '1:1060733275150:ios:769e7898c41ed3c3cb805f',
    messagingSenderId: '1060733275150',
    projectId: 'fruit-app-ef788',
    storageBucket: 'fruit-app-ef788.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAawBbigakkSzHZAt_mCAe0axLN9tHml6k',
    appId: '1:1060733275150:web:23ff6206c8154ae4cb805f',
    messagingSenderId: '1060733275150',
    projectId: 'fruit-app-ef788',
    authDomain: 'fruit-app-ef788.firebaseapp.com',
    storageBucket: 'fruit-app-ef788.firebasestorage.app',
    measurementId: 'G-BSV1K1CCF7',
  );
}
